
/* autogenerated from lv_math.orc */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifndef _ORC_INTEGER_TYPEDEFS_
#define _ORC_INTEGER_TYPEDEFS_
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
#include <stdint.h>
typedef int8_t orc_int8;
typedef int16_t orc_int16;
typedef int32_t orc_int32;
typedef int64_t orc_int64;
typedef uint8_t orc_uint8;
typedef uint16_t orc_uint16;
typedef uint32_t orc_uint32;
typedef uint64_t orc_uint64;
#define ORC_UINT64_C(x) UINT64_C(x)
#elif defined(_MSC_VER)
typedef signed __int8 orc_int8;
typedef signed __int16 orc_int16;
typedef signed __int32 orc_int32;
typedef signed __int64 orc_int64;
typedef unsigned __int8 orc_uint8;
typedef unsigned __int16 orc_uint16;
typedef unsigned __int32 orc_uint32;
typedef unsigned __int64 orc_uint64;
#define ORC_UINT64_C(x) (x##Ui64)
#define inline __inline
#else
#include <limits.h>
typedef signed char orc_int8;
typedef short orc_int16;
typedef int orc_int32;
typedef unsigned char orc_uint8;
typedef unsigned short orc_uint16;
typedef unsigned int orc_uint32;
#if INT_MAX == LONG_MAX
typedef long long orc_int64;
typedef unsigned long long orc_uint64;
#define ORC_UINT64_C(x) (x##ULL)
#else
typedef long orc_int64;
typedef unsigned long orc_uint64;
#define ORC_UINT64_C(x) (x##UL)
#endif
#endif
typedef union { orc_int16 i; orc_int8 x2[2]; } orc_union16;
typedef union { orc_int32 i; float f; orc_int16 x2[2]; orc_int8 x4[4]; } orc_union32;
typedef union { orc_int64 i; double f; orc_int32 x2[2]; float x2f[2]; orc_int16 x4[4]; } orc_union64;
#endif
#ifndef ORC_RESTRICT
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
#define ORC_RESTRICT restrict
#elif defined(__GNUC__) && __GNUC__ >= 4
#define ORC_RESTRICT __restrict__
#else
#define ORC_RESTRICT
#endif
#endif

#ifndef DISABLE_ORC
#include <orc/orc.h>
#endif
void visual_math_simd_mul_floats_float (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n);
void visual_math_simd_mul_floats_floats (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, const float * ORC_RESTRICT s2, int n);
void visual_math_simd_add_floats_float (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n);
void visual_math_simd_floats_to_int32s (orc_uint32 * ORC_RESTRICT d1, float * ORC_RESTRICT d2, int n);
void visual_math_simd_int32s_to_floats (orc_uint32 * ORC_RESTRICT d1, float * ORC_RESTRICT d2, int n);
void visual_math_simd_sqrt_floats (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, int n);
void visual_math_simd_floats_to_int32s_mul_float (orc_uint32 * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n);
void visual_math_simd_int32s_to_floats_mul_float (float * ORC_RESTRICT d1, const orc_uint32 * ORC_RESTRICT s1, float p1, int n);
void visual_math_simd_complex_norm (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, const float * ORC_RESTRICT s2, int n);
void visual_math_simd_complex_scaled_norm (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, const float * ORC_RESTRICT s2, float p1, int n);
void visual_math_simd_denorm_floats_to_int32s (orc_uint32 * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n);
void visual_math_simd_denorm_neg_floats_to_int32s (orc_uint32 * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n);


/* begin Orc C target preamble */
#define ORC_CLAMP(x,a,b) ((x)<(a) ? (a) : ((x)>(b) ? (b) : (x)))
#define ORC_ABS(a) ((a)<0 ? -(a) : (a))
#define ORC_MIN(a,b) ((a)<(b) ? (a) : (b))
#define ORC_MAX(a,b) ((a)>(b) ? (a) : (b))
#define ORC_SB_MAX 127
#define ORC_SB_MIN (-1-ORC_SB_MAX)
#define ORC_UB_MAX 255
#define ORC_UB_MIN 0
#define ORC_SW_MAX 32767
#define ORC_SW_MIN (-1-ORC_SW_MAX)
#define ORC_UW_MAX 65535
#define ORC_UW_MIN 0
#define ORC_SL_MAX 2147483647
#define ORC_SL_MIN (-1-ORC_SL_MAX)
#define ORC_UL_MAX 4294967295U
#define ORC_UL_MIN 0
#define ORC_CLAMP_SB(x) ORC_CLAMP(x,ORC_SB_MIN,ORC_SB_MAX)
#define ORC_CLAMP_UB(x) ORC_CLAMP(x,ORC_UB_MIN,ORC_UB_MAX)
#define ORC_CLAMP_SW(x) ORC_CLAMP(x,ORC_SW_MIN,ORC_SW_MAX)
#define ORC_CLAMP_UW(x) ORC_CLAMP(x,ORC_UW_MIN,ORC_UW_MAX)
#define ORC_CLAMP_SL(x) ORC_CLAMP(x,ORC_SL_MIN,ORC_SL_MAX)
#define ORC_CLAMP_UL(x) ORC_CLAMP(x,ORC_UL_MIN,ORC_UL_MAX)
#define ORC_SWAP_W(x) ((((x)&0xff)<<8) | (((x)&0xff00)>>8))
#define ORC_SWAP_L(x) ((((x)&0xff)<<24) | (((x)&0xff00)<<8) | (((x)&0xff0000)>>8) | (((x)&0xff000000)>>24))
#define ORC_SWAP_Q(x) ((((x)&ORC_UINT64_C(0xff))<<56) | (((x)&ORC_UINT64_C(0xff00))<<40) | (((x)&ORC_UINT64_C(0xff0000))<<24) | (((x)&ORC_UINT64_C(0xff000000))<<8) | (((x)&ORC_UINT64_C(0xff00000000))>>8) | (((x)&ORC_UINT64_C(0xff0000000000))>>24) | (((x)&ORC_UINT64_C(0xff000000000000))>>40) | (((x)&ORC_UINT64_C(0xff00000000000000))>>56))
#define ORC_PTR_OFFSET(ptr,offset) ((void *)(((unsigned char *)(ptr)) + (offset)))
#define ORC_DENORMAL(x) ((x) & ((((x)&0x7f800000) == 0) ? 0xff800000 : 0xffffffff))
#define ORC_ISNAN(x) ((((x)&0x7f800000) == 0x7f800000) && (((x)&0x007fffff) != 0))
#define ORC_DENORMAL_DOUBLE(x) ((x) & ((((x)&ORC_UINT64_C(0x7ff0000000000000)) == 0) ? ORC_UINT64_C(0xfff0000000000000) : ORC_UINT64_C(0xffffffffffffffff)))
#define ORC_ISNAN_DOUBLE(x) ((((x)&ORC_UINT64_C(0x7ff0000000000000)) == ORC_UINT64_C(0x7ff0000000000000)) && (((x)&ORC_UINT64_C(0x000fffffffffffff)) != 0))
#ifndef ORC_RESTRICT
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
#define ORC_RESTRICT restrict
#elif defined(__GNUC__) && __GNUC__ >= 4
#define ORC_RESTRICT __restrict__
#else
#define ORC_RESTRICT
#endif
#endif
/* end Orc C target preamble */



/* visual_math_simd_mul_floats_float */
#ifdef DISABLE_ORC
void
visual_math_simd_mul_floats_float (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n){
  int i;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  orc_union32 var32;
  orc_union32 var33;
  orc_union32 var34;

  ptr0 = (orc_union32 *)d1;
  ptr4 = (orc_union32 *)s1;

    /* 1: loadpl */
    var33.f = p1;

  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var32 = ptr4[i];
    /* 2: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var32.i);
       _src2.i = ORC_DENORMAL(var33.i);
       _dest1.f = _src1.f * _src2.f;
       var34.i = ORC_DENORMAL(_dest1.i);
    }
    /* 3: storel */
    ptr0[i] = var34;
  }

}

#else
static void
_backup_visual_math_simd_mul_floats_float (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  orc_union32 var32;
  orc_union32 var33;
  orc_union32 var34;

  ptr0 = (orc_union32 *)ex->arrays[0];
  ptr4 = (orc_union32 *)ex->arrays[4];

    /* 1: loadpl */
    var33.i = ex->params[24];

  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var32 = ptr4[i];
    /* 2: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var32.i);
       _src2.i = ORC_DENORMAL(var33.i);
       _dest1.f = _src1.f * _src2.f;
       var34.i = ORC_DENORMAL(_dest1.i);
    }
    /* 3: storel */
    ptr0[i] = var34;
  }

}

void
visual_math_simd_mul_floats_float (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  static int p_inited = 0;
  static OrcCode *c = 0;
  void (*func) (OrcExecutor *);

  if (!p_inited) {
    orc_once_mutex_lock ();
    if (!p_inited) {
      OrcProgram *p;

      p = orc_program_new ();
      orc_program_set_name (p, "visual_math_simd_mul_floats_float");
      orc_program_set_backup_function (p, _backup_visual_math_simd_mul_floats_float);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_parameter_float (p, 4, "p1");

      orc_program_append_2 (p, "mulf", 0, ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_P1, ORC_VAR_D1);

      orc_program_compile (p);
      c = orc_program_take_code (p);
      orc_program_free (p);
    }
    p_inited = TRUE;
    orc_once_mutex_unlock ();
  }
  ex->arrays[ORC_VAR_A2] = c;
  ex->program = 0;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = (void *)s1;
  {
    orc_union32 tmp;
    tmp.f = p1;
    ex->params[ORC_VAR_P1] = tmp.i;
  }

  func = c->exec;
  func (ex);
}
#endif


/* visual_math_simd_mul_floats_floats */
#ifdef DISABLE_ORC
void
visual_math_simd_mul_floats_floats (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, const float * ORC_RESTRICT s2, int n){
  int i;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  const orc_union32 * ORC_RESTRICT ptr5;
  orc_union32 var32;
  orc_union32 var33;
  orc_union32 var34;

  ptr0 = (orc_union32 *)d1;
  ptr4 = (orc_union32 *)s1;
  ptr5 = (orc_union32 *)s2;


  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var32 = ptr4[i];
    /* 1: loadl */
    var33 = ptr5[i];
    /* 2: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var32.i);
       _src2.i = ORC_DENORMAL(var33.i);
       _dest1.f = _src1.f * _src2.f;
       var34.i = ORC_DENORMAL(_dest1.i);
    }
    /* 3: storel */
    ptr0[i] = var34;
  }

}

#else
static void
_backup_visual_math_simd_mul_floats_floats (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  const orc_union32 * ORC_RESTRICT ptr5;
  orc_union32 var32;
  orc_union32 var33;
  orc_union32 var34;

  ptr0 = (orc_union32 *)ex->arrays[0];
  ptr4 = (orc_union32 *)ex->arrays[4];
  ptr5 = (orc_union32 *)ex->arrays[5];


  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var32 = ptr4[i];
    /* 1: loadl */
    var33 = ptr5[i];
    /* 2: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var32.i);
       _src2.i = ORC_DENORMAL(var33.i);
       _dest1.f = _src1.f * _src2.f;
       var34.i = ORC_DENORMAL(_dest1.i);
    }
    /* 3: storel */
    ptr0[i] = var34;
  }

}

void
visual_math_simd_mul_floats_floats (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, const float * ORC_RESTRICT s2, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  static int p_inited = 0;
  static OrcCode *c = 0;
  void (*func) (OrcExecutor *);

  if (!p_inited) {
    orc_once_mutex_lock ();
    if (!p_inited) {
      OrcProgram *p;

      p = orc_program_new ();
      orc_program_set_name (p, "visual_math_simd_mul_floats_floats");
      orc_program_set_backup_function (p, _backup_visual_math_simd_mul_floats_floats);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_source (p, 4, "s2");

      orc_program_append_2 (p, "mulf", 0, ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_S2, ORC_VAR_D1);

      orc_program_compile (p);
      c = orc_program_take_code (p);
      orc_program_free (p);
    }
    p_inited = TRUE;
    orc_once_mutex_unlock ();
  }
  ex->arrays[ORC_VAR_A2] = c;
  ex->program = 0;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = (void *)s1;
  ex->arrays[ORC_VAR_S2] = (void *)s2;

  func = c->exec;
  func (ex);
}
#endif


/* visual_math_simd_add_floats_float */
#ifdef DISABLE_ORC
void
visual_math_simd_add_floats_float (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n){
  int i;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  orc_union32 var32;
  orc_union32 var33;
  orc_union32 var34;

  ptr0 = (orc_union32 *)d1;
  ptr4 = (orc_union32 *)s1;

    /* 1: loadpl */
    var33.f = p1;

  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var32 = ptr4[i];
    /* 2: addf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var32.i);
       _src2.i = ORC_DENORMAL(var33.i);
       _dest1.f = _src1.f + _src2.f;
       var34.i = ORC_DENORMAL(_dest1.i);
    }
    /* 3: storel */
    ptr0[i] = var34;
  }

}

#else
static void
_backup_visual_math_simd_add_floats_float (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  orc_union32 var32;
  orc_union32 var33;
  orc_union32 var34;

  ptr0 = (orc_union32 *)ex->arrays[0];
  ptr4 = (orc_union32 *)ex->arrays[4];

    /* 1: loadpl */
    var33.i = ex->params[24];

  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var32 = ptr4[i];
    /* 2: addf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var32.i);
       _src2.i = ORC_DENORMAL(var33.i);
       _dest1.f = _src1.f + _src2.f;
       var34.i = ORC_DENORMAL(_dest1.i);
    }
    /* 3: storel */
    ptr0[i] = var34;
  }

}

void
visual_math_simd_add_floats_float (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  static int p_inited = 0;
  static OrcCode *c = 0;
  void (*func) (OrcExecutor *);

  if (!p_inited) {
    orc_once_mutex_lock ();
    if (!p_inited) {
      OrcProgram *p;

      p = orc_program_new ();
      orc_program_set_name (p, "visual_math_simd_add_floats_float");
      orc_program_set_backup_function (p, _backup_visual_math_simd_add_floats_float);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_parameter_float (p, 4, "p1");

      orc_program_append_2 (p, "addf", 0, ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_P1, ORC_VAR_D1);

      orc_program_compile (p);
      c = orc_program_take_code (p);
      orc_program_free (p);
    }
    p_inited = TRUE;
    orc_once_mutex_unlock ();
  }
  ex->arrays[ORC_VAR_A2] = c;
  ex->program = 0;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = (void *)s1;
  {
    orc_union32 tmp;
    tmp.f = p1;
    ex->params[ORC_VAR_P1] = tmp.i;
  }

  func = c->exec;
  func (ex);
}
#endif


/* visual_math_simd_floats_to_int32s */
#ifdef DISABLE_ORC
void
visual_math_simd_floats_to_int32s (orc_uint32 * ORC_RESTRICT d1, float * ORC_RESTRICT d2, int n){
  int i;
  orc_union32 * ORC_RESTRICT ptr0;
  orc_union32 * ORC_RESTRICT ptr1;
  orc_union32 var32;
  orc_union32 var33;

  ptr0 = (orc_union32 *)d1;
  ptr1 = (orc_union32 *)d2;


  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var32 = ptr1[i];
    /* 1: convfl */
    {
       int tmp;
       tmp = (int)var32.f;
       if (tmp == 0x80000000 && !(var32.i&0x80000000)) tmp = 0x7fffffff;
       var33.i = tmp;
    }
    /* 2: storel */
    ptr0[i] = var33;
  }

}

#else
static void
_backup_visual_math_simd_floats_to_int32s (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union32 * ORC_RESTRICT ptr0;
  orc_union32 * ORC_RESTRICT ptr1;
  orc_union32 var32;
  orc_union32 var33;

  ptr0 = (orc_union32 *)ex->arrays[0];
  ptr1 = (orc_union32 *)ex->arrays[1];


  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var32 = ptr1[i];
    /* 1: convfl */
    {
       int tmp;
       tmp = (int)var32.f;
       if (tmp == 0x80000000 && !(var32.i&0x80000000)) tmp = 0x7fffffff;
       var33.i = tmp;
    }
    /* 2: storel */
    ptr0[i] = var33;
  }

}

void
visual_math_simd_floats_to_int32s (orc_uint32 * ORC_RESTRICT d1, float * ORC_RESTRICT d2, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  static int p_inited = 0;
  static OrcCode *c = 0;
  void (*func) (OrcExecutor *);

  if (!p_inited) {
    orc_once_mutex_lock ();
    if (!p_inited) {
      OrcProgram *p;

      p = orc_program_new ();
      orc_program_set_name (p, "visual_math_simd_floats_to_int32s");
      orc_program_set_backup_function (p, _backup_visual_math_simd_floats_to_int32s);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_destination (p, 4, "d2");

      orc_program_append_2 (p, "convfl", 0, ORC_VAR_D1, ORC_VAR_D2, ORC_VAR_D1, ORC_VAR_D1);

      orc_program_compile (p);
      c = orc_program_take_code (p);
      orc_program_free (p);
    }
    p_inited = TRUE;
    orc_once_mutex_unlock ();
  }
  ex->arrays[ORC_VAR_A2] = c;
  ex->program = 0;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_D2] = d2;

  func = c->exec;
  func (ex);
}
#endif


/* visual_math_simd_int32s_to_floats */
#ifdef DISABLE_ORC
void
visual_math_simd_int32s_to_floats (orc_uint32 * ORC_RESTRICT d1, float * ORC_RESTRICT d2, int n){
  int i;
  orc_union32 * ORC_RESTRICT ptr0;
  orc_union32 * ORC_RESTRICT ptr1;
  orc_union32 var32;
  orc_union32 var33;

  ptr0 = (orc_union32 *)d1;
  ptr1 = (orc_union32 *)d2;


  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var32 = ptr1[i];
    /* 1: convlf */
     var33.f = var32.i;
    /* 2: storel */
    ptr0[i] = var33;
  }

}

#else
static void
_backup_visual_math_simd_int32s_to_floats (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union32 * ORC_RESTRICT ptr0;
  orc_union32 * ORC_RESTRICT ptr1;
  orc_union32 var32;
  orc_union32 var33;

  ptr0 = (orc_union32 *)ex->arrays[0];
  ptr1 = (orc_union32 *)ex->arrays[1];


  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var32 = ptr1[i];
    /* 1: convlf */
     var33.f = var32.i;
    /* 2: storel */
    ptr0[i] = var33;
  }

}

void
visual_math_simd_int32s_to_floats (orc_uint32 * ORC_RESTRICT d1, float * ORC_RESTRICT d2, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  static int p_inited = 0;
  static OrcCode *c = 0;
  void (*func) (OrcExecutor *);

  if (!p_inited) {
    orc_once_mutex_lock ();
    if (!p_inited) {
      OrcProgram *p;

      p = orc_program_new ();
      orc_program_set_name (p, "visual_math_simd_int32s_to_floats");
      orc_program_set_backup_function (p, _backup_visual_math_simd_int32s_to_floats);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_destination (p, 4, "d2");

      orc_program_append_2 (p, "convlf", 0, ORC_VAR_D1, ORC_VAR_D2, ORC_VAR_D1, ORC_VAR_D1);

      orc_program_compile (p);
      c = orc_program_take_code (p);
      orc_program_free (p);
    }
    p_inited = TRUE;
    orc_once_mutex_unlock ();
  }
  ex->arrays[ORC_VAR_A2] = c;
  ex->program = 0;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_D2] = d2;

  func = c->exec;
  func (ex);
}
#endif


/* visual_math_simd_sqrt_floats */
#ifdef DISABLE_ORC
void
visual_math_simd_sqrt_floats (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, int n){
  int i;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  orc_union32 var32;
  orc_union32 var33;

  ptr0 = (orc_union32 *)d1;
  ptr4 = (orc_union32 *)s1;


  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var32 = ptr4[i];
    /* 1: sqrtf */
    {
       orc_union32 _src1;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var32.i);
       _dest1.f = sqrt(_src1.f);
       var33.i = ORC_DENORMAL(_dest1.i);
    }
    /* 2: storel */
    ptr0[i] = var33;
  }

}

#else
static void
_backup_visual_math_simd_sqrt_floats (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  orc_union32 var32;
  orc_union32 var33;

  ptr0 = (orc_union32 *)ex->arrays[0];
  ptr4 = (orc_union32 *)ex->arrays[4];


  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var32 = ptr4[i];
    /* 1: sqrtf */
    {
       orc_union32 _src1;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var32.i);
       _dest1.f = sqrt(_src1.f);
       var33.i = ORC_DENORMAL(_dest1.i);
    }
    /* 2: storel */
    ptr0[i] = var33;
  }

}

void
visual_math_simd_sqrt_floats (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  static int p_inited = 0;
  static OrcCode *c = 0;
  void (*func) (OrcExecutor *);

  if (!p_inited) {
    orc_once_mutex_lock ();
    if (!p_inited) {
      OrcProgram *p;

      p = orc_program_new ();
      orc_program_set_name (p, "visual_math_simd_sqrt_floats");
      orc_program_set_backup_function (p, _backup_visual_math_simd_sqrt_floats);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 4, "s1");

      orc_program_append_2 (p, "sqrtf", 0, ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_D1, ORC_VAR_D1);

      orc_program_compile (p);
      c = orc_program_take_code (p);
      orc_program_free (p);
    }
    p_inited = TRUE;
    orc_once_mutex_unlock ();
  }
  ex->arrays[ORC_VAR_A2] = c;
  ex->program = 0;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = (void *)s1;

  func = c->exec;
  func (ex);
}
#endif


/* visual_math_simd_floats_to_int32s_mul_float */
#ifdef DISABLE_ORC
void
visual_math_simd_floats_to_int32s_mul_float (orc_uint32 * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n){
  int i;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  orc_union32 var33;
  orc_union32 var34;
  orc_union32 var35;
  orc_union32 var36;

  ptr0 = (orc_union32 *)d1;
  ptr4 = (orc_union32 *)s1;

    /* 2: loadpl */
    var34.f = p1;

  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var33 = ptr4[i];
    /* 1: convfl */
    {
       int tmp;
       tmp = (int)var33.f;
       if (tmp == 0x80000000 && !(var33.i&0x80000000)) tmp = 0x7fffffff;
       var36.i = tmp;
    }
    /* 3: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var34.i);
       _src2.i = ORC_DENORMAL(var36.i);
       _dest1.f = _src1.f * _src2.f;
       var35.i = ORC_DENORMAL(_dest1.i);
    }
    /* 4: storel */
    ptr0[i] = var35;
  }

}

#else
static void
_backup_visual_math_simd_floats_to_int32s_mul_float (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  orc_union32 var33;
  orc_union32 var34;
  orc_union32 var35;
  orc_union32 var36;

  ptr0 = (orc_union32 *)ex->arrays[0];
  ptr4 = (orc_union32 *)ex->arrays[4];

    /* 2: loadpl */
    var34.i = ex->params[24];

  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var33 = ptr4[i];
    /* 1: convfl */
    {
       int tmp;
       tmp = (int)var33.f;
       if (tmp == 0x80000000 && !(var33.i&0x80000000)) tmp = 0x7fffffff;
       var36.i = tmp;
    }
    /* 3: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var34.i);
       _src2.i = ORC_DENORMAL(var36.i);
       _dest1.f = _src1.f * _src2.f;
       var35.i = ORC_DENORMAL(_dest1.i);
    }
    /* 4: storel */
    ptr0[i] = var35;
  }

}

void
visual_math_simd_floats_to_int32s_mul_float (orc_uint32 * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  static int p_inited = 0;
  static OrcCode *c = 0;
  void (*func) (OrcExecutor *);

  if (!p_inited) {
    orc_once_mutex_lock ();
    if (!p_inited) {
      OrcProgram *p;

      p = orc_program_new ();
      orc_program_set_name (p, "visual_math_simd_floats_to_int32s_mul_float");
      orc_program_set_backup_function (p, _backup_visual_math_simd_floats_to_int32s_mul_float);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_parameter_float (p, 4, "p1");
      orc_program_add_temporary (p, 4, "t1");

      orc_program_append_2 (p, "convfl", 0, ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1, ORC_VAR_D1);
      orc_program_append_2 (p, "mulf", 0, ORC_VAR_D1, ORC_VAR_P1, ORC_VAR_T1, ORC_VAR_D1);

      orc_program_compile (p);
      c = orc_program_take_code (p);
      orc_program_free (p);
    }
    p_inited = TRUE;
    orc_once_mutex_unlock ();
  }
  ex->arrays[ORC_VAR_A2] = c;
  ex->program = 0;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = (void *)s1;
  {
    orc_union32 tmp;
    tmp.f = p1;
    ex->params[ORC_VAR_P1] = tmp.i;
  }

  func = c->exec;
  func (ex);
}
#endif


/* visual_math_simd_int32s_to_floats_mul_float */
#ifdef DISABLE_ORC
void
visual_math_simd_int32s_to_floats_mul_float (float * ORC_RESTRICT d1, const orc_uint32 * ORC_RESTRICT s1, float p1, int n){
  int i;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  orc_union32 var33;
  orc_union32 var34;
  orc_union32 var35;
  orc_union32 var36;

  ptr0 = (orc_union32 *)d1;
  ptr4 = (orc_union32 *)s1;

    /* 2: loadpl */
    var34.f = p1;

  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var33 = ptr4[i];
    /* 1: convlf */
     var36.f = var33.i;
    /* 3: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var34.i);
       _src2.i = ORC_DENORMAL(var36.i);
       _dest1.f = _src1.f * _src2.f;
       var35.i = ORC_DENORMAL(_dest1.i);
    }
    /* 4: storel */
    ptr0[i] = var35;
  }

}

#else
static void
_backup_visual_math_simd_int32s_to_floats_mul_float (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  orc_union32 var33;
  orc_union32 var34;
  orc_union32 var35;
  orc_union32 var36;

  ptr0 = (orc_union32 *)ex->arrays[0];
  ptr4 = (orc_union32 *)ex->arrays[4];

    /* 2: loadpl */
    var34.i = ex->params[24];

  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var33 = ptr4[i];
    /* 1: convlf */
     var36.f = var33.i;
    /* 3: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var34.i);
       _src2.i = ORC_DENORMAL(var36.i);
       _dest1.f = _src1.f * _src2.f;
       var35.i = ORC_DENORMAL(_dest1.i);
    }
    /* 4: storel */
    ptr0[i] = var35;
  }

}

void
visual_math_simd_int32s_to_floats_mul_float (float * ORC_RESTRICT d1, const orc_uint32 * ORC_RESTRICT s1, float p1, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  static int p_inited = 0;
  static OrcCode *c = 0;
  void (*func) (OrcExecutor *);

  if (!p_inited) {
    orc_once_mutex_lock ();
    if (!p_inited) {
      OrcProgram *p;

      p = orc_program_new ();
      orc_program_set_name (p, "visual_math_simd_int32s_to_floats_mul_float");
      orc_program_set_backup_function (p, _backup_visual_math_simd_int32s_to_floats_mul_float);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_parameter_float (p, 4, "p1");
      orc_program_add_temporary (p, 4, "t1");

      orc_program_append_2 (p, "convlf", 0, ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1, ORC_VAR_D1);
      orc_program_append_2 (p, "mulf", 0, ORC_VAR_D1, ORC_VAR_P1, ORC_VAR_T1, ORC_VAR_D1);

      orc_program_compile (p);
      c = orc_program_take_code (p);
      orc_program_free (p);
    }
    p_inited = TRUE;
    orc_once_mutex_unlock ();
  }
  ex->arrays[ORC_VAR_A2] = c;
  ex->program = 0;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = (void *)s1;
  {
    orc_union32 tmp;
    tmp.f = p1;
    ex->params[ORC_VAR_P1] = tmp.i;
  }

  func = c->exec;
  func (ex);
}
#endif


/* visual_math_simd_complex_norm */
#ifdef DISABLE_ORC
void
visual_math_simd_complex_norm (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, const float * ORC_RESTRICT s2, int n){
  int i;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  const orc_union32 * ORC_RESTRICT ptr5;
  orc_union32 var34;
  orc_union32 var35;
  orc_union32 var36;
  orc_union32 var37;
  orc_union32 var38;
  orc_union32 var39;
  orc_union32 var40;
  orc_union32 var41;

  ptr0 = (orc_union32 *)d1;
  ptr4 = (orc_union32 *)s1;
  ptr5 = (orc_union32 *)s2;


  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var34 = ptr4[i];
    /* 1: loadl */
    var35 = ptr4[i];
    /* 2: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var34.i);
       _src2.i = ORC_DENORMAL(var35.i);
       _dest1.f = _src1.f * _src2.f;
       var39.i = ORC_DENORMAL(_dest1.i);
    }
    /* 3: loadl */
    var36 = ptr5[i];
    /* 4: loadl */
    var37 = ptr5[i];
    /* 5: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var36.i);
       _src2.i = ORC_DENORMAL(var37.i);
       _dest1.f = _src1.f * _src2.f;
       var40.i = ORC_DENORMAL(_dest1.i);
    }
    /* 6: addf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var39.i);
       _src2.i = ORC_DENORMAL(var40.i);
       _dest1.f = _src1.f + _src2.f;
       var41.i = ORC_DENORMAL(_dest1.i);
    }
    /* 7: sqrtf */
    {
       orc_union32 _src1;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var41.i);
       _dest1.f = sqrt(_src1.f);
       var38.i = ORC_DENORMAL(_dest1.i);
    }
    /* 8: storel */
    ptr0[i] = var38;
  }

}

#else
static void
_backup_visual_math_simd_complex_norm (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  const orc_union32 * ORC_RESTRICT ptr5;
  orc_union32 var34;
  orc_union32 var35;
  orc_union32 var36;
  orc_union32 var37;
  orc_union32 var38;
  orc_union32 var39;
  orc_union32 var40;
  orc_union32 var41;

  ptr0 = (orc_union32 *)ex->arrays[0];
  ptr4 = (orc_union32 *)ex->arrays[4];
  ptr5 = (orc_union32 *)ex->arrays[5];


  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var34 = ptr4[i];
    /* 1: loadl */
    var35 = ptr4[i];
    /* 2: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var34.i);
       _src2.i = ORC_DENORMAL(var35.i);
       _dest1.f = _src1.f * _src2.f;
       var39.i = ORC_DENORMAL(_dest1.i);
    }
    /* 3: loadl */
    var36 = ptr5[i];
    /* 4: loadl */
    var37 = ptr5[i];
    /* 5: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var36.i);
       _src2.i = ORC_DENORMAL(var37.i);
       _dest1.f = _src1.f * _src2.f;
       var40.i = ORC_DENORMAL(_dest1.i);
    }
    /* 6: addf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var39.i);
       _src2.i = ORC_DENORMAL(var40.i);
       _dest1.f = _src1.f + _src2.f;
       var41.i = ORC_DENORMAL(_dest1.i);
    }
    /* 7: sqrtf */
    {
       orc_union32 _src1;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var41.i);
       _dest1.f = sqrt(_src1.f);
       var38.i = ORC_DENORMAL(_dest1.i);
    }
    /* 8: storel */
    ptr0[i] = var38;
  }

}

void
visual_math_simd_complex_norm (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, const float * ORC_RESTRICT s2, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  static int p_inited = 0;
  static OrcCode *c = 0;
  void (*func) (OrcExecutor *);

  if (!p_inited) {
    orc_once_mutex_lock ();
    if (!p_inited) {
      OrcProgram *p;

      p = orc_program_new ();
      orc_program_set_name (p, "visual_math_simd_complex_norm");
      orc_program_set_backup_function (p, _backup_visual_math_simd_complex_norm);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_source (p, 4, "s2");
      orc_program_add_temporary (p, 4, "t1");
      orc_program_add_temporary (p, 4, "t2");

      orc_program_append_2 (p, "mulf", 0, ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append_2 (p, "mulf", 0, ORC_VAR_T2, ORC_VAR_S2, ORC_VAR_S2, ORC_VAR_D1);
      orc_program_append_2 (p, "addf", 0, ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_T2, ORC_VAR_D1);
      orc_program_append_2 (p, "sqrtf", 0, ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_D1, ORC_VAR_D1);

      orc_program_compile (p);
      c = orc_program_take_code (p);
      orc_program_free (p);
    }
    p_inited = TRUE;
    orc_once_mutex_unlock ();
  }
  ex->arrays[ORC_VAR_A2] = c;
  ex->program = 0;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = (void *)s1;
  ex->arrays[ORC_VAR_S2] = (void *)s2;

  func = c->exec;
  func (ex);
}
#endif


/* visual_math_simd_complex_scaled_norm */
#ifdef DISABLE_ORC
void
visual_math_simd_complex_scaled_norm (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, const float * ORC_RESTRICT s2, float p1, int n){
  int i;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  const orc_union32 * ORC_RESTRICT ptr5;
  orc_union32 var34;
  orc_union32 var35;
  orc_union32 var36;
  orc_union32 var37;
  orc_union32 var38;
  orc_union32 var39;
  orc_union32 var40;
  orc_union32 var41;
  orc_union32 var42;
  orc_union32 var43;

  ptr0 = (orc_union32 *)d1;
  ptr4 = (orc_union32 *)s1;
  ptr5 = (orc_union32 *)s2;

    /* 8: loadpl */
    var38.f = p1;

  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var34 = ptr4[i];
    /* 1: loadl */
    var35 = ptr4[i];
    /* 2: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var34.i);
       _src2.i = ORC_DENORMAL(var35.i);
       _dest1.f = _src1.f * _src2.f;
       var40.i = ORC_DENORMAL(_dest1.i);
    }
    /* 3: loadl */
    var36 = ptr5[i];
    /* 4: loadl */
    var37 = ptr5[i];
    /* 5: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var36.i);
       _src2.i = ORC_DENORMAL(var37.i);
       _dest1.f = _src1.f * _src2.f;
       var41.i = ORC_DENORMAL(_dest1.i);
    }
    /* 6: addf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var40.i);
       _src2.i = ORC_DENORMAL(var41.i);
       _dest1.f = _src1.f + _src2.f;
       var42.i = ORC_DENORMAL(_dest1.i);
    }
    /* 7: sqrtf */
    {
       orc_union32 _src1;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var42.i);
       _dest1.f = sqrt(_src1.f);
       var43.i = ORC_DENORMAL(_dest1.i);
    }
    /* 9: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var43.i);
       _src2.i = ORC_DENORMAL(var38.i);
       _dest1.f = _src1.f * _src2.f;
       var39.i = ORC_DENORMAL(_dest1.i);
    }
    /* 10: storel */
    ptr0[i] = var39;
  }

}

#else
static void
_backup_visual_math_simd_complex_scaled_norm (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  const orc_union32 * ORC_RESTRICT ptr5;
  orc_union32 var34;
  orc_union32 var35;
  orc_union32 var36;
  orc_union32 var37;
  orc_union32 var38;
  orc_union32 var39;
  orc_union32 var40;
  orc_union32 var41;
  orc_union32 var42;
  orc_union32 var43;

  ptr0 = (orc_union32 *)ex->arrays[0];
  ptr4 = (orc_union32 *)ex->arrays[4];
  ptr5 = (orc_union32 *)ex->arrays[5];

    /* 8: loadpl */
    var38.i = ex->params[24];

  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var34 = ptr4[i];
    /* 1: loadl */
    var35 = ptr4[i];
    /* 2: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var34.i);
       _src2.i = ORC_DENORMAL(var35.i);
       _dest1.f = _src1.f * _src2.f;
       var40.i = ORC_DENORMAL(_dest1.i);
    }
    /* 3: loadl */
    var36 = ptr5[i];
    /* 4: loadl */
    var37 = ptr5[i];
    /* 5: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var36.i);
       _src2.i = ORC_DENORMAL(var37.i);
       _dest1.f = _src1.f * _src2.f;
       var41.i = ORC_DENORMAL(_dest1.i);
    }
    /* 6: addf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var40.i);
       _src2.i = ORC_DENORMAL(var41.i);
       _dest1.f = _src1.f + _src2.f;
       var42.i = ORC_DENORMAL(_dest1.i);
    }
    /* 7: sqrtf */
    {
       orc_union32 _src1;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var42.i);
       _dest1.f = sqrt(_src1.f);
       var43.i = ORC_DENORMAL(_dest1.i);
    }
    /* 9: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var43.i);
       _src2.i = ORC_DENORMAL(var38.i);
       _dest1.f = _src1.f * _src2.f;
       var39.i = ORC_DENORMAL(_dest1.i);
    }
    /* 10: storel */
    ptr0[i] = var39;
  }

}

void
visual_math_simd_complex_scaled_norm (float * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, const float * ORC_RESTRICT s2, float p1, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  static int p_inited = 0;
  static OrcCode *c = 0;
  void (*func) (OrcExecutor *);

  if (!p_inited) {
    orc_once_mutex_lock ();
    if (!p_inited) {
      OrcProgram *p;

      p = orc_program_new ();
      orc_program_set_name (p, "visual_math_simd_complex_scaled_norm");
      orc_program_set_backup_function (p, _backup_visual_math_simd_complex_scaled_norm);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_source (p, 4, "s2");
      orc_program_add_parameter_float (p, 4, "p1");
      orc_program_add_temporary (p, 4, "t1");
      orc_program_add_temporary (p, 4, "t2");

      orc_program_append_2 (p, "mulf", 0, ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append_2 (p, "mulf", 0, ORC_VAR_T2, ORC_VAR_S2, ORC_VAR_S2, ORC_VAR_D1);
      orc_program_append_2 (p, "addf", 0, ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_T2, ORC_VAR_D1);
      orc_program_append_2 (p, "sqrtf", 0, ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_D1, ORC_VAR_D1);
      orc_program_append_2 (p, "mulf", 0, ORC_VAR_D1, ORC_VAR_T2, ORC_VAR_P1, ORC_VAR_D1);

      orc_program_compile (p);
      c = orc_program_take_code (p);
      orc_program_free (p);
    }
    p_inited = TRUE;
    orc_once_mutex_unlock ();
  }
  ex->arrays[ORC_VAR_A2] = c;
  ex->program = 0;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = (void *)s1;
  ex->arrays[ORC_VAR_S2] = (void *)s2;
  {
    orc_union32 tmp;
    tmp.f = p1;
    ex->params[ORC_VAR_P1] = tmp.i;
  }

  func = c->exec;
  func (ex);
}
#endif


/* visual_math_simd_denorm_floats_to_int32s */
#ifdef DISABLE_ORC
void
visual_math_simd_denorm_floats_to_int32s (orc_uint32 * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n){
  int i;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  orc_union32 var34;
  orc_union32 var35;
  orc_union32 var36;
  orc_union32 var37;
  orc_union32 var38;
  orc_union32 var39;
  orc_union32 var40;
  orc_union32 var41;

  ptr0 = (orc_union32 *)d1;
  ptr4 = (orc_union32 *)s1;

    /* 1: loadpl */
    var35.i = (int)0x00000000; /* 0 or 0f */
    /* 3: loadpl */
    var36.i = (int)0x3f800000; /* 1065353216 or 5.26354e-315f */
    /* 5: loadpl */
    var37.f = p1;

  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var34 = ptr4[i];
    /* 2: maxf */
    {
      orc_union32 _src1;
      orc_union32 _src2;
      _src1.i = ORC_DENORMAL(var34.i);
      _src2.i = ORC_DENORMAL(var35.i);
      if (ORC_ISNAN(_src1.i)) var39.i = _src1.i;
      else if (ORC_ISNAN(_src2.i)) var39.i = _src2.i;
      else var39.i = (_src1.f > _src2.f) ? _src1.i : _src2.i;
    }
    /* 4: minf */
    {
      orc_union32 _src1;
      orc_union32 _src2;
      _src1.i = ORC_DENORMAL(var39.i);
      _src2.i = ORC_DENORMAL(var36.i);
      if (ORC_ISNAN(_src1.i)) var40.i = _src1.i;
      else if (ORC_ISNAN(_src2.i)) var40.i = _src2.i;
      else var40.i = (_src1.f < _src2.f) ? _src1.i : _src2.i;
    }
    /* 6: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var40.i);
       _src2.i = ORC_DENORMAL(var37.i);
       _dest1.f = _src1.f * _src2.f;
       var41.i = ORC_DENORMAL(_dest1.i);
    }
    /* 7: convfl */
    {
       int tmp;
       tmp = (int)var41.f;
       if (tmp == 0x80000000 && !(var41.i&0x80000000)) tmp = 0x7fffffff;
       var38.i = tmp;
    }
    /* 8: storel */
    ptr0[i] = var38;
  }

}

#else
static void
_backup_visual_math_simd_denorm_floats_to_int32s (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  orc_union32 var34;
  orc_union32 var35;
  orc_union32 var36;
  orc_union32 var37;
  orc_union32 var38;
  orc_union32 var39;
  orc_union32 var40;
  orc_union32 var41;

  ptr0 = (orc_union32 *)ex->arrays[0];
  ptr4 = (orc_union32 *)ex->arrays[4];

    /* 1: loadpl */
    var35.i = (int)0x00000000; /* 0 or 0f */
    /* 3: loadpl */
    var36.i = (int)0x3f800000; /* 1065353216 or 5.26354e-315f */
    /* 5: loadpl */
    var37.i = ex->params[24];

  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var34 = ptr4[i];
    /* 2: maxf */
    {
      orc_union32 _src1;
      orc_union32 _src2;
      _src1.i = ORC_DENORMAL(var34.i);
      _src2.i = ORC_DENORMAL(var35.i);
      if (ORC_ISNAN(_src1.i)) var39.i = _src1.i;
      else if (ORC_ISNAN(_src2.i)) var39.i = _src2.i;
      else var39.i = (_src1.f > _src2.f) ? _src1.i : _src2.i;
    }
    /* 4: minf */
    {
      orc_union32 _src1;
      orc_union32 _src2;
      _src1.i = ORC_DENORMAL(var39.i);
      _src2.i = ORC_DENORMAL(var36.i);
      if (ORC_ISNAN(_src1.i)) var40.i = _src1.i;
      else if (ORC_ISNAN(_src2.i)) var40.i = _src2.i;
      else var40.i = (_src1.f < _src2.f) ? _src1.i : _src2.i;
    }
    /* 6: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var40.i);
       _src2.i = ORC_DENORMAL(var37.i);
       _dest1.f = _src1.f * _src2.f;
       var41.i = ORC_DENORMAL(_dest1.i);
    }
    /* 7: convfl */
    {
       int tmp;
       tmp = (int)var41.f;
       if (tmp == 0x80000000 && !(var41.i&0x80000000)) tmp = 0x7fffffff;
       var38.i = tmp;
    }
    /* 8: storel */
    ptr0[i] = var38;
  }

}

void
visual_math_simd_denorm_floats_to_int32s (orc_uint32 * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  static int p_inited = 0;
  static OrcCode *c = 0;
  void (*func) (OrcExecutor *);

  if (!p_inited) {
    orc_once_mutex_lock ();
    if (!p_inited) {
      OrcProgram *p;

      p = orc_program_new ();
      orc_program_set_name (p, "visual_math_simd_denorm_floats_to_int32s");
      orc_program_set_backup_function (p, _backup_visual_math_simd_denorm_floats_to_int32s);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_constant (p, 4, 0x00000000, "c1");
      orc_program_add_constant (p, 4, 0x3f800000, "c2");
      orc_program_add_parameter_float (p, 4, "p1");
      orc_program_add_temporary (p, 4, "t1");
      orc_program_add_temporary (p, 4, "t2");

      orc_program_append_2 (p, "maxf", 0, ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_C1, ORC_VAR_D1);
      orc_program_append_2 (p, "minf", 0, ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_C2, ORC_VAR_D1);
      orc_program_append_2 (p, "mulf", 0, ORC_VAR_T1, ORC_VAR_T2, ORC_VAR_P1, ORC_VAR_D1);
      orc_program_append_2 (p, "convfl", 0, ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_D1, ORC_VAR_D1);

      orc_program_compile (p);
      c = orc_program_take_code (p);
      orc_program_free (p);
    }
    p_inited = TRUE;
    orc_once_mutex_unlock ();
  }
  ex->arrays[ORC_VAR_A2] = c;
  ex->program = 0;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = (void *)s1;
  {
    orc_union32 tmp;
    tmp.f = p1;
    ex->params[ORC_VAR_P1] = tmp.i;
  }

  func = c->exec;
  func (ex);
}
#endif


/* visual_math_simd_denorm_neg_floats_to_int32s */
#ifdef DISABLE_ORC
void
visual_math_simd_denorm_neg_floats_to_int32s (orc_uint32 * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n){
  int i;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  orc_union32 var34;
  orc_union32 var35;
  orc_union32 var36;
  orc_union32 var37;
  orc_union32 var38;
  orc_union32 var39;
  orc_union32 var40;
  orc_union32 var41;
  orc_union32 var42;
  orc_union32 var43;
  orc_union32 var44;
  orc_union32 var45;

  ptr0 = (orc_union32 *)d1;
  ptr4 = (orc_union32 *)s1;

    /* 1: loadpl */
    var35.i = (int)0xbf800000; /* -1082130432 or -nanf */
    /* 3: loadpl */
    var36.i = (int)0x3f800000; /* 1065353216 or 5.26354e-315f */
    /* 5: loadpl */
    var37.i = (int)0x3f800000; /* 1065353216 or 5.26354e-315f */
    /* 7: loadpl */
    var38.i = (int)0x3f000000; /* 1056964608 or 5.2221e-315f */
    /* 9: loadpl */
    var39.f = p1;

  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var34 = ptr4[i];
    /* 2: maxf */
    {
      orc_union32 _src1;
      orc_union32 _src2;
      _src1.i = ORC_DENORMAL(var34.i);
      _src2.i = ORC_DENORMAL(var35.i);
      if (ORC_ISNAN(_src1.i)) var41.i = _src1.i;
      else if (ORC_ISNAN(_src2.i)) var41.i = _src2.i;
      else var41.i = (_src1.f > _src2.f) ? _src1.i : _src2.i;
    }
    /* 4: minf */
    {
      orc_union32 _src1;
      orc_union32 _src2;
      _src1.i = ORC_DENORMAL(var41.i);
      _src2.i = ORC_DENORMAL(var36.i);
      if (ORC_ISNAN(_src1.i)) var42.i = _src1.i;
      else if (ORC_ISNAN(_src2.i)) var42.i = _src2.i;
      else var42.i = (_src1.f < _src2.f) ? _src1.i : _src2.i;
    }
    /* 6: addf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var42.i);
       _src2.i = ORC_DENORMAL(var37.i);
       _dest1.f = _src1.f + _src2.f;
       var43.i = ORC_DENORMAL(_dest1.i);
    }
    /* 8: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var43.i);
       _src2.i = ORC_DENORMAL(var38.i);
       _dest1.f = _src1.f * _src2.f;
       var44.i = ORC_DENORMAL(_dest1.i);
    }
    /* 10: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var44.i);
       _src2.i = ORC_DENORMAL(var39.i);
       _dest1.f = _src1.f * _src2.f;
       var45.i = ORC_DENORMAL(_dest1.i);
    }
    /* 11: convfl */
    {
       int tmp;
       tmp = (int)var45.f;
       if (tmp == 0x80000000 && !(var45.i&0x80000000)) tmp = 0x7fffffff;
       var40.i = tmp;
    }
    /* 12: storel */
    ptr0[i] = var40;
  }

}

#else
static void
_backup_visual_math_simd_denorm_neg_floats_to_int32s (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union32 * ORC_RESTRICT ptr0;
  const orc_union32 * ORC_RESTRICT ptr4;
  orc_union32 var34;
  orc_union32 var35;
  orc_union32 var36;
  orc_union32 var37;
  orc_union32 var38;
  orc_union32 var39;
  orc_union32 var40;
  orc_union32 var41;
  orc_union32 var42;
  orc_union32 var43;
  orc_union32 var44;
  orc_union32 var45;

  ptr0 = (orc_union32 *)ex->arrays[0];
  ptr4 = (orc_union32 *)ex->arrays[4];

    /* 1: loadpl */
    var35.i = (int)0xbf800000; /* -1082130432 or -nanf */
    /* 3: loadpl */
    var36.i = (int)0x3f800000; /* 1065353216 or 5.26354e-315f */
    /* 5: loadpl */
    var37.i = (int)0x3f800000; /* 1065353216 or 5.26354e-315f */
    /* 7: loadpl */
    var38.i = (int)0x3f000000; /* 1056964608 or 5.2221e-315f */
    /* 9: loadpl */
    var39.i = ex->params[24];

  for (i = 0; i < n; i++) {
    /* 0: loadl */
    var34 = ptr4[i];
    /* 2: maxf */
    {
      orc_union32 _src1;
      orc_union32 _src2;
      _src1.i = ORC_DENORMAL(var34.i);
      _src2.i = ORC_DENORMAL(var35.i);
      if (ORC_ISNAN(_src1.i)) var41.i = _src1.i;
      else if (ORC_ISNAN(_src2.i)) var41.i = _src2.i;
      else var41.i = (_src1.f > _src2.f) ? _src1.i : _src2.i;
    }
    /* 4: minf */
    {
      orc_union32 _src1;
      orc_union32 _src2;
      _src1.i = ORC_DENORMAL(var41.i);
      _src2.i = ORC_DENORMAL(var36.i);
      if (ORC_ISNAN(_src1.i)) var42.i = _src1.i;
      else if (ORC_ISNAN(_src2.i)) var42.i = _src2.i;
      else var42.i = (_src1.f < _src2.f) ? _src1.i : _src2.i;
    }
    /* 6: addf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var42.i);
       _src2.i = ORC_DENORMAL(var37.i);
       _dest1.f = _src1.f + _src2.f;
       var43.i = ORC_DENORMAL(_dest1.i);
    }
    /* 8: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var43.i);
       _src2.i = ORC_DENORMAL(var38.i);
       _dest1.f = _src1.f * _src2.f;
       var44.i = ORC_DENORMAL(_dest1.i);
    }
    /* 10: mulf */
    {
       orc_union32 _src1;
       orc_union32 _src2;
       orc_union32 _dest1;
       _src1.i = ORC_DENORMAL(var44.i);
       _src2.i = ORC_DENORMAL(var39.i);
       _dest1.f = _src1.f * _src2.f;
       var45.i = ORC_DENORMAL(_dest1.i);
    }
    /* 11: convfl */
    {
       int tmp;
       tmp = (int)var45.f;
       if (tmp == 0x80000000 && !(var45.i&0x80000000)) tmp = 0x7fffffff;
       var40.i = tmp;
    }
    /* 12: storel */
    ptr0[i] = var40;
  }

}

void
visual_math_simd_denorm_neg_floats_to_int32s (orc_uint32 * ORC_RESTRICT d1, const float * ORC_RESTRICT s1, float p1, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  static int p_inited = 0;
  static OrcCode *c = 0;
  void (*func) (OrcExecutor *);

  if (!p_inited) {
    orc_once_mutex_lock ();
    if (!p_inited) {
      OrcProgram *p;

      p = orc_program_new ();
      orc_program_set_name (p, "visual_math_simd_denorm_neg_floats_to_int32s");
      orc_program_set_backup_function (p, _backup_visual_math_simd_denorm_neg_floats_to_int32s);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_constant (p, 4, 0xbf800000, "c1");
      orc_program_add_constant (p, 4, 0x3f800000, "c2");
      orc_program_add_constant (p, 4, 0x3f000000, "c3");
      orc_program_add_parameter_float (p, 4, "p1");
      orc_program_add_temporary (p, 4, "t1");
      orc_program_add_temporary (p, 4, "t2");

      orc_program_append_2 (p, "maxf", 0, ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_C1, ORC_VAR_D1);
      orc_program_append_2 (p, "minf", 0, ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_C2, ORC_VAR_D1);
      orc_program_append_2 (p, "addf", 0, ORC_VAR_T1, ORC_VAR_T2, ORC_VAR_C2, ORC_VAR_D1);
      orc_program_append_2 (p, "mulf", 0, ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_C3, ORC_VAR_D1);
      orc_program_append_2 (p, "mulf", 0, ORC_VAR_T1, ORC_VAR_T2, ORC_VAR_P1, ORC_VAR_D1);
      orc_program_append_2 (p, "convfl", 0, ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_D1, ORC_VAR_D1);

      orc_program_compile (p);
      c = orc_program_take_code (p);
      orc_program_free (p);
    }
    p_inited = TRUE;
    orc_once_mutex_unlock ();
  }
  ex->arrays[ORC_VAR_A2] = c;
  ex->program = 0;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = (void *)s1;
  {
    orc_union32 tmp;
    tmp.f = p1;
    ex->params[ORC_VAR_P1] = tmp.i;
  }

  func = c->exec;
  func (ex);
}
#endif


